name: kutmod
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - pip=22.3
  - python=3.10.6
  - pip:
      - scikit-network==0.27.1
      - tk==0.1.0
      - ttkbootstrap==1.9.0
